# Site settings
title: "Apprenez à coder vous mêmes"
logo: s-logo-a.png # image from https://www.flickr.com/photos/lwr/5496279831/in/set-72157594159055823
email: erwan@bootstrapyourcodingskills.com
description: "Apprenez à coder vous mêmes pour créer votre propore site web ou pour développez vos activités ou pour mieux communiquer avec vos développeurs."
url: "" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/
twitter_username: jekyllrb
github_username:  BootstrapYourCodingSkills

permalink: pretty
paginate: 5

# Build settings
markdown: kramdown
#highlighter: rouge

gems:
  - jekyll-sitemap
  - jekyll-paginate
